# Generated by Django 3.2.6 on 2022-03-23 05:39

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('youtube', '0001_initial'),
        ('artist', '0001_initial'),
        ('category', '0001_initial'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id_songs', models.AutoField(primary_key=True, serialize=False)),
                ('code_song', models.IntegerField(default=0)),
                ('title_song', models.CharField(max_length=100)),
                ('alias1', models.CharField(max_length=100)),
                ('alias2', models.CharField(max_length=100)),
                ('alias3', models.CharField(max_length=100)),
                ('path', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='.'), upload_to='media/songs')),
                ('xvoc', models.IntegerField(default=0)),
                ('voc', models.IntegerField(default=0)),
                ('vol', models.IntegerField(default=0)),
                ('Foto', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='.'), upload_to='media/songs')),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('id_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre')),
                ('id_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.root')),
                ('id_ytb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.youtube')),
            ],
        ),
    ]
