# Generated by Django 3.2.6 on 2022-03-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_root_path'),
        ('genre', '0001_initial'),
        ('category', '0001_initial'),
        ('youtube', '0001_initial'),
        ('artist', '0001_initial'),
        ('songs', '0002_alter_song_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='category.category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='genre.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id_root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='root.root'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id_ytb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ytb', to='youtube.youtube'),
        ),
    ]
