# Generated by Django 3.2.6 on 2022-03-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20220323_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='path',
            new_name='paths',
        ),
    ]
