# Generated by Django 3.2.6 on 2022-03-23 05:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id_artist', models.AutoField(primary_key=True, serialize=False)),
                ('code_artist', models.IntegerField(default=0)),
                ('artist_name', models.CharField(max_length=100)),
                ('aliasname1', models.CharField(max_length=100)),
                ('aliasname2', models.CharField(max_length=100)),
                ('aliasname3', models.CharField(max_length=100)),
                ('foto_artist', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='.'), upload_to='media/artist')),
            ],
        ),
    ]
