# Generated by Django 3.2.6 on 2022-03-29 06:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='foto_artist',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='.'), upload_to='media/artist'),
        ),
    ]
