# Generated by Django 3.2.6 on 2022-03-29 06:51

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_foto_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='foto_artist',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, storage=django.core.files.storage.FileSystemStorage(location='.'), upload_to='media/artist'),
            preserve_default=False,
        ),
    ]
