# Generated by Django 3.2.6 on 2022-04-04 03:45

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_foto_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='foto_artist',
            field=versatileimagefield.fields.VersatileImageField(upload_to='media/artist', verbose_name='Image'),
        ),
    ]
