# Generated by Django 3.2.6 on 2022-04-04 03:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20220404_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='artist',
            name='foto_artist',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='.'), upload_to='media/artist'),
        ),
    ]
