# Generated by Django 3.2.6 on 2022-03-23 05:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='root',
            fields=[
                ('id_root', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='.'), upload_to='media/songs')),
            ],
        ),
    ]
