# Generated by Django 3.2.6 on 2022-03-23 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='root',
            name='path',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
