# Generated by Django 3.2.6 on 2022-03-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_root_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='root',
            old_name='path',
            new_name='paths',
        ),
    ]
